// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGLoLMRbeTh0Si88lizZNwI_JcAoumXP8',
    appId: '1:283822590793:web:e95c51b55746f637242898',
    messagingSenderId: '283822590793',
    projectId: 'travello-app-14b2f',
    authDomain: 'travello-app-14b2f.firebaseapp.com',
    storageBucket: 'travello-app-14b2f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmOpBMGh87cwk62EUc3OcSnjCKZu3LWSc',
    appId: '1:283822590793:android:255e02ad782e0457242898',
    messagingSenderId: '283822590793',
    projectId: 'travello-app-14b2f',
    storageBucket: 'travello-app-14b2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgsFWe8Tm7ck669O-nMs3lP1ek4hKPoNo',
    appId: '1:283822590793:ios:426bfae95288a832242898',
    messagingSenderId: '283822590793',
    projectId: 'travello-app-14b2f',
    storageBucket: 'travello-app-14b2f.firebasestorage.app',
    iosBundleId: 'com.example.travellApp',
  );
}
